# Generated by Django 5.1.5 on 2025-02-27 07:25

from django.db import migrations
from django.utils.text import slugify

categories = [
    "Python Technologies",
    "Mobile Development",
    "Computer Science",
    "DevOps",
    "Machine Learning",
    "Web Development",
    "Databases",
    "Computer Programming",
]


courses = [
    {
        "title": "Intro to Python",
        "category": "Python Technologies",
        "description": "Learn the basics of Python.",
        "tags": ["Python", "Programming Basics"],
        "lessons": [
            {"title": "Variables and Data Types"},
            {"title": "Control Flow and Loops"},
        ],
    },
    {
        "title": "React for Beginners",
        "category": "Web Development",
        "description": "Introduction to building web apps with React.",
        "tags": ["React", "JavaScript", "Frontend"],
        "lessons": [
            {"title": "Introduction to JSX"},
            {"title": "Component Lifecycle"},
        ],
    },
    {
        "title": "Data Structures and Algorithms",
        "category": "Computer Science",
        "description": "Learn essential DSA concepts.",
        "tags": ["DSA", "Algorithms", "Computer Science"],
        "lessons": [
            {"title": "Arrays and Linked Lists"},
            {"title": "Sorting and Searching"},
        ],
    },
    {
        "title": "Machine Learning 101",
        "category": "Machine Learning",
        "description": "An intro to machine learning techniques.",
        "tags": ["Machine Learning", "AI", "Data Science"],
        "lessons": [
            {"title": "Supervised Learning"},
            {"title": "Unsupervised Learning"},
        ],
    },
    {
        "title": "Web Development with Django",
        "category": "Web Development",
        "description": "Building web apps with Django.",
        "tags": ["Django", "Python", "Backend"],
        "lessons": [
            {"title": "Django Models"},
            {"title": "Django Views and Templates"},
        ],
    },
]


def create_initial_data(apps, schema_editor):
    Category = apps.get_model("apis", "Category")
    Course = apps.get_model("apis", "Course")
    Tag = apps.get_model("apis", "Tag")
    Lesson = apps.get_model("apis", "Lesson")

    category_map = {}
    for c in categories:
        category, _ = Category.objects.get_or_create(title=c, defaults={"slug": slugify(c)})
        category_map[c] = category

    for course in courses:
        category = category_map[course["category"]]
        course_obj, _ = Course.objects.get_or_create(
            title=course["title"],
            category=category,
            defaults={"description": course["description"], "slug": slugify(course["title"])},
        )

        for tag_name in course["tags"]:
            tag, _ = Tag.objects.get_or_create(title=tag_name, defaults={"slug": slugify(tag_name)})
            course_obj.tags.add(tag)

        for lesson_data in course["lessons"]:
            lesson_obj, _ = Lesson.objects.get_or_create(
                title=lesson_data["title"],
                course=course_obj,
                defaults={"slug": slugify(lesson_data["title"])},
            )

            for tag in course_obj.tags.all():
                lesson_obj.tags.add(tag)


class Migration(migrations.Migration):

    dependencies = [
        ("apis", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_initial_data),
    ]
