# Generated by Django 5.1.5 on 2025-02-09 04:45

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_auto_20250209_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, default=None, help_text='Upload banner of the course', null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='courses/%Y/%m/%d/'),
        ),
    ]
